version: '3.8'

services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    image: demise1426/haryeom-fe
    ports:
      - "3000:3000"
    container_name: haryeom-fe
    environment:
      - NODE_ENV=production
    restart: always
